// src/components/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useStore } from '~/store'

const store = useStore()

const videoPageEnabled = computed({
  get: () => store.state.settings.videoPageEnabled,
  set: (value) =>
    store.commit('settings/setVideoPageEnabled', {
      videoPageEnabled: value,
    }),
})
const channelPageEnabled = computed({
  get: () => store.state.settings.channelPageEnabled,
  set: (value) =>
    store.commit('settings/setChannelPageEnabled', {
      channelPageEnabled: value,
    }),
})
</script>

<template>
  <v-app>
    <v-main class="fill-height">
      <v-container fluid>
        <v-switch
          v-model="videoPageEnabled"
          color="primary"
          density="compact"
          hide-details
          label="Stop Autoplay on Video Page"
        />
        <v-switch
          v-model="channelPageEnabled"
          color="primary"
          density="compact"
          hide-details
          label="Stop Autoplay on Channel Page"
        />
      </v-container>
    </v-main>
  </v-app>
</template>

<style lang="scss">
html {
  overflow-y: hidden;
}
</style>

<style lang="scss" scoped>
.v-application {
  width: 320px;
}
</style>

// src/components/App.tsx
import {
  CssBaseline,
  FormControlLabel,
  FormGroup,
  GlobalStyles,
  Switch,
} from '@mui/material'
import { ChangeEvent } from 'react'
import { StoreProvider } from '~/contexts/StoreContext'
import { useAppDispatch, useAppSelector } from '~/store'
import {
  selectChannelPageEnabled,
  selectVideoPageEnabled,
  setChannelPageEnabled,
  setVideoPageEnabled,
} from '~/store/settings'

const InnerApp = () => {
  const channelPageEnabled = useAppSelector(selectChannelPageEnabled)
  const videoPageEnabled = useAppSelector(selectVideoPageEnabled)
  const dispatch = useAppDispatch()

  const handleChangeChannelPageEnabled = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setChannelPageEnabled(value))
  }

  const handleChangeVideoPageEnabled = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setVideoPageEnabled(value))
  }

  return (
    <FormGroup sx={{ mx: 2, my: 1 }}>
      <FormControlLabel
        control={
          <Switch
            checked={channelPageEnabled}
            onChange={handleChangeChannelPageEnabled}
          />
        }
        label="Stop Autoplay on Video Page"
      />
      <FormControlLabel
        control={
          <Switch
            checked={videoPageEnabled}
            onChange={handleChangeVideoPageEnabled}
          />
        }
        label="Stop Autoplay on Channel Page"
      />
    </FormGroup>
  )
}

const App = () => {
  return (
    <StoreProvider>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { overflowY: 'hidden', width: 330 },
        }}
      />
      <InnerApp />
    </StoreProvider>
  )
}

export default App
